import numpy as np
import matplotlib.pyplot as plt
import Util
from scipy.interpolate import CubicSpline

def wavToPixel(wavelength, w0=1.16236340e+04, a0=1.33788072e-01, round=True):
    """
    Utility function to convert a wavelength to its pixel coordinates using a linear conversion function.
    Inverse of PixelToWav

    Args:
        wavelength(float): The wavelength you wish to convert in Angstroms
        w0(float, optional): The wavelength of the first pixel in Angstroms. If not given, defaults to value for vph300 HK.
        a0(float, optional): The linear scale factor in pixels per Angstrom. If not given, defaults to value for vph300 HK.
        round(boolean, optional): Should the result be rounded to the nearest integer. Default: True

    Returns:
        Pixel Coord:  Pixel value as either a float if rounding is off, or an int if rounding is on.
    """
    if not round:
        return (wavelength-w0)*a0
    else:
        return int(np.round((wavelength-w0)*a0))
def pixelToWav(pixel, w, a):
    """
    Utility function to convert a pixel coordinate to a wavelength using a linear conversion function.
    Inverse of wavToPixel

    Args:
        pixel(float): The pixel coodinate you wish to convert
        w(float): The wavelength of the first pixel in Angstroms
        a(float): The linear scale factor in pixels per Angstrom
        round(bool): Should the result be rounded to the nearest integer. Default: True

    Returns:
        Wavelength: The wavelgnth that your pixel would fall at
    """
    return pixel/a+w
    
def absResid(data, model):
    """
    Utility function to see how well data and a model agree (lower is better)

    Args:
        data(array): The data you wish to compare to
        model(array): The model you wish to compare

    Returns:
        The sum of the absolute differences between the model and the data.
    """
    return np.sum(np.abs(data-model))

def calcModel(lines, arrLen, w0, s, width=2.5, offset=0, power=5):
    """
    Function to calcuate a 1D spectral model using a linelist.

    Args:
        lines(list): The line list with the comparison lines. This list should be formatted as detailed in createLineList in Util.py
        arrLen(int): The length of the data array you want to compare to
        w0(float): The wavelength of the first pixel, in Angstroms
        s(float): The linear scale factor in pixels per Angstrom.
        width(float, optional): The half width of the Lorentizan of model lines in pixels. Defaults to 2.5 pixels
        offset(float, optional): The offset of the Lorentizan models. Defaults to zero.
        power(float, optional): The power of the Lorentizan model, which correponds to how square the lines are. Defaults to 5; a normal Lorentizan has this as 2.

    Returns:
        A numpy array containing the intensities of the model.
    """
    model=np.zeros(arrLen)
    xs = np.arange(0, arrLen)
    for l in lines:
        x0 = wavToPixel(float(l[1]), w0, a0=s)
        model += LorentzLine(xs, x0, l[4], width, offset, power)
    return model

def updateLinearFit(event, updatefig, line, lines, model):
    """
    Helper function to make the plots generated by calcLinearFit interactive
    """
    model *= 0
    xs = np.arange(0, len(model))
    for l in lines:
        x0 = wavToPixel(l[1], w0=event.ydata, a0=event.xdata)
        model += LorentzLine(xs, x0, l[4], 2.5, 0, 5)
    line.set_ydata(model/np.max(model))
    updatefig.canvas.draw()
    updatefig.canvas.flush_events()

def calcLinearFit(data, lines, minW0, maxW0, minScale, maxScale, resW = 200, resS = 200, viewPlots = True):
    """
    Function to calculate the parameters of best fit for a linear conversion from pixel space to wavelength space.
    When viewPlots is set to true, interactive plots will be generated, with an x at the best fit parameters on the residual heatmap.
    The second plot shows the data overlaid with the model of best fit. If a point on the heatmap plot is clicked, the model plot will
    be regenerated using the parameters of the click location. 

    Args:
        data(array): The 1D spectral data that you are fitting to.
        lines(list): The line list with the comparison lines. This list should be formatted as detailed in createLineList in Util.py
        minW0(float): The starting point for the wavelength of the first pixel in Angstroms.
        maxW0(float): The ending point for the wavelenght of the first pixel in Angstroms.
        minScale(float): The starting point for the linear scale factor in pixels per Angstroms.
        maxScale(float): The ending point for the linear scale factor in pixels per Angstroms.
        resW(int, optional): The resolution (number of search steps) in the starting wavelength dimention. Default is 200
        resS(int, optional): The resolution (number of search steps) in the linear scale factor dimention. Default is 200
        viewPlots(boolean, optional): Should visualization plots be generated? Default is True.

    Returns:
        wBest(float): The best found starting wavelength
        sBest(float): The best found linear scale factor.

    """
    params = np.zeros((int(resW), int(resS)))
    xs = np.arange(0, len(data))
    ws = np.linspace(minW0, maxW0, int(resW))
    ses = np.linspace(minScale, maxScale, int(resS))
    for w in range(len(ws)):
        for s in range(len(ses)):
            model = np.zeros_like(data)
            for l in lines:
                x0 = wavToPixel(l[1], w0=ws[w], a0=ses[s])
                model += LorentzLine(xs, x0, l[4], 2.5, 0, 5)
            params[w,s] = absResid(data/np.max(data), model/np.max(model))
    loc = np.argmin(params)
    wBest = ws[loc//resS]
    sBest = ses[loc%resS]
    if viewPlots:
        fig1, ax1 = plt.subplots(1,1)
        mask = np.logical_not(np.isnan(params))
        img = ax1.imshow(params, vmin=np.min(params[mask]), vmax=np.max(params[mask]), extent=[minScale, maxScale, maxW0, minW0])
        fig1.colorbar(img)
        ax1.plot(sBest, wBest, "rx")
        ax1.set_xlabel("Scale value (Pixels/Angstrom)")
        ax1.set_xlabel("Starting wavelength (A)")
        ax1.set_aspect("auto")

        fig2, ax2 = plt.subplots(1,1)
        ax2.plot(data/np.max(data), label="data")
        model = np.zeros_like(data)
        for l in lines:
            x0 = wavToPixel(l[1], w0=wBest, a0=sBest)
            model += LorentzLine(xs, x0, l[4], 2.5, 0, 5)
        line, = ax2.plot(model/np.max(model), label="model")
        ax2.legend()
        ax2.set_xlabel("Wavelength (A)")
        ax2.set_ylabel("Normalized Intensity")
        cid = fig1.canvas.mpl_connect('button_press_event', lambda e: updateLinearFit(e, fig2, line, lines, model))


    
    return wBest, sBest 


def continuum(I, medRange=20, thresh=7, maxRun=10, debug=False):
    """
    Function to appoximate the continuum of a spectrum

    Args:
        I(array): Array of intensities
        medRange(int, optional): Radius of the median filter applied to the data. Default is 20 pixels.
        thresh(float, optional): Minimum slope needed to mark as a portion of a line. Default is 7
        maxRun(int, optional): Maximum number of flat points that are ignored in a row. Useful if more rising slopes are found than falling slopes. Default is 10 data points.
        debug(boolean, optional): Create debug plots showing the stages of continuum subtraction. Default is False.

    Returns:
        Cubic interpolation that generates the continuum when passed an index.
    """
    res = I[1:]-I[0:-1]
    res[0:-1] = (res[0:-1] + res[1:])/2 #blur somewhat to increase SNR
    inc = res>thresh
    dec = res<-thresh
    plateau = np.logical_and(res<thresh, res>-thresh)

    contMask = np.logical_not(np.isnan(res))
    rising = False
    runLength = 0
    for i in range(len(res)):
        if inc[i]:
            contMask[i]=False
            rising=True
            runLength=0
        if dec[i]:
            contMask[i]=False
            rising=False
        if rising:
            contMask[i]=False
            runLength+=1
            if runLength>maxRun:
                rising=False
    
    med = I[:-1][contMask]
    tmp = np.copy(med)
    for i in range(len(med)):
        med[i] = np.median(tmp[np.max([0,i-medRange]):np.min([len(med)-1,i+medRange])])

    index = np.arange(len(I)-1)
    interp = CubicSpline(index[contMask], med)

    if debug:
        fig, ax = plt.subplots(3,1, figsize=(6,7))
        
        ax[0].plot(index,I[:-1], ".")
        ax[1].plot(index[plateau],res[plateau], ".", color="black")
        ax[1].plot(index[inc],res[inc], ".", color="blue")
        ax[1].plot(index[dec],res[dec], ".", color="red")
        ax[1].plot(index[contMask],res[contMask], ".", color="green")
        ax[2].plot(index[contMask], I[:-1][contMask])
        ax[2].plot(index[contMask], med)
        ax[2].plot(index, interp(index))
    return interp
    
def convert2Dto1D(data2D, y1, y2):
    """
    Utility function to convert a 2D image to a 1D image

    Args:
        data2D(2D array): The data of the 2D array
        y1(int): The staring row to average into a 1D array
        y2(int): The ending row to average into a 1D array

    Returns:
        1D array containing intensities
    """
    return np.average(data2D[y1:y2,:], axis=0)

def gaussLine(x, pos, A, width, offset, power):
    """
    Utility function to calculate a generalized Gaussian line

    Args:
        x(array): The positions you want to evaluate the line at.
        pos(float): The center position of the line.
        A(float): The height of the line.
        width(float): The half-width of the line.
        offset(float): The vertical offset of the line.
        power(float): The power of the line, where a higher power is more square (A normal gaussian will have this set to two).

    Returns:
        1D array containing intensities of the line.
    """
    return A*np.exp(-np.abs(x-pos)**power/(width**power))+offset

def gaussWidthToFWHM(width, power):
    """
    Utility function to calculate the FWHM of a generalized Gaussian

    Args:
        width(float): The half-width of the line.
        power(float): The power of the line, where a higher power is more square (A normal gaussian will have this set to two).

    Returns:
        The FWHM of the line
    """
    return 2*width*(-np.log(1/2))**(1/power)

def LorentzLine(x, pos, A, width, offset, power):
    """
    Utility function to calculate a generalized Lorentizan line

    Args:
        x(array): The positions you want to evaluate the line at.
        pos(float): The center position of the line.
        A(float): The height of the line.
        width(float): The half-width of the line.
        offset(float): The vertical offset of the line.
        power(float): The power of the line, where a higher power is more square (A normal Lorentizan will have this set to two).

    Returns:
        1D array containing intensities of the line.
    """
    return A/(1+np.abs((x-pos)/width)**power)+offset

def LorentzWidthToFWHM(width):
    """
    Utility function to calculate the FWHM of a generalized Lorenzian

    Args:
        width(float): The half-width of the line.

    Returns:
        The FWHM of the line
    """
    return 2*width

