import numpy as np
import pandas as pd

def createLineList(path, writePath=None, mergedLines = ["Hg", "Kr", "Ar", "Xe"], minAmp = 100, maxAmp=np.inf, minWav = 14000, maxWav=26000):
    """
    Function to create line lists from predicted lines from a partiular line list kindly provided by Joe Durback, which is a 3-column text file delimited by spaces.
    The first column is the wavelength in Angstroms, the second is the relative intensity, and the third is the ion type. Outputs either a 2D list
    where the columns are formatted like PypeIt line lists, with the option to save a PypeIt formatted line list dat file.

    Args:
        path(string): Path to the line list provuded by Joe.
        writePath(string, optional): Path to the .dat file that will be saved in PypeIt line list style. Default: None, which does not save any file.
        mergedLines(list of strings, optional): List of ions that will be loaded into the returned line list. Default: ["Hg", "Kr", "Ar", "Xe"], which will load all of the ions provided in Joe's line list
        minAmp(float, optional): Minimum line amplitude that will be loaded into the line list. Defualt: 100.
        maxAmp(float, optional): Maximum line amplitude that will be loaded into the line list. Default: infinity
        minWav(float, optional): Minimum wavelength that loaded lines will be. Default: 14000 Angstroms.
        maxWav(float, optional): Maximum wavelength that loaded lines will be. Default: 26000 Angstroms.

    Returns:
        2D list containing formatted like a normal PypeIt line list. The list is in Row-Major order and the columns are [ion (string), wavelength (Angstroms), NIST, Instr, amplitude (float), Source (string)]
    """
    data = pd.read_csv(path, delimiter=" ")
    retData = []
    for row in range(len(data)):
        if (data.values[row][1] < minAmp or data.values[row][1] > maxAmp or data.values[row][0] < minWav or data.values[row][0] > maxWav):
            continue
        ion = data.values[row][3][0:2]
        if ion in mergedLines:
            retData.append([f"{ion}I",data.values[row][0],1,data.values[row][2],data.values[row][1],data.values[row][3]])

    if writePath is not None:
        with open(writePath, mode="w") as file:
            file.write(f"| ion |      wave | NIST | Instr | amplitude |       Source |\n")
            text = ""
            for i in range(len(retData)):
                text += f"| {retData[i][0]} | {retData[i][1]:>9.3f} |    1 |{retData[i][3]:>6.0f} | {retData[i][4]:>9.1f} | {retData[i][5]} |\n"
            file.write(text)
    return retData

def loadNISTData(path, writePath=None, mergedLines = ["Hg", "Kr", "Ar", "Xe"], minAmp = 1, maxAmp=np.inf, minWav = 14000, maxWav=26000):
    """
    Function to create line lists from predicted lines from a line list generated by NIST. Outputs either a 2D list
    where the columns are formatted like PypeIt line lists, with the option to save a PypeIt formatted line list dat file.
    Your line list must have the columns:
    Ion       |        Air wav (Å) |Unc. (Å)| Ritz Wav Air (Å)   |Unc. (Å)|  Amp  | Aki (s^-1) | Acc. | Lower level | Upper level |Type| TP 

    Args:
        path(string): Path to the NIST line list.
        writePath(string, optional): Path to the .dat file that will be saved in PypeIt line list style. Default: None, which does not save any file.
        mergedLines(list of strings, optional): List of ions that will be loaded into the returned line list. Default: ["Hg", "Kr", "Ar", "Xe"], which will load all of the ions provided in Joe's line list
        minAmp(float, optional): Minimum line amplitude that will be loaded into the line list. Defualt: 100.
        maxAmp(float, optional): Maximum line amplitude that will be loaded into the line list. Default: infinity
        minWav(float, optional): Minimum wavelength that loaded lines will be. Default: 14000 Angstroms.
        maxWav(float, optional): Maximum wavelength that loaded lines will be. Default: 26000 Angstroms.

    Returns:
        2D list containing formatted like a normal PypeIt line list. The list is in Row-Major order and the columns are [ion (string), wavelength (Angstroms), NIST, Instr, amplitude (float), Source (string)]
    """
    data=pd.read_csv(path, delimiter="|")
    retData = []
    for row in range(len(data)):
        if (data.values[row][5] < minAmp or data.values[row][5] > maxAmp or data.values[row][1] < minWav or data.values[row][1] > maxWav):
            continue
        ion = data.values[row][0][0:2]
        if ion in mergedLines:
            retData.append([f"{ion}I",data.values[row][1],1,1,data.values[row][5],"NIST"])

    if writePath is not None:
        with open(writePath, mode="w") as file:
            file.write(f"| ion |      wave | NIST | Instr | amplitude |       Source |\n")
            text = ""
            for i in range(len(retData)):
                text += f"| {retData[i][0]} | {retData[i][1]:>9.3f} |    1 |{retData[i][3]:>6.0f} | {retData[i][4]:>9.1f} | {retData[i][5]} |\n"
            file.write(text)
    return retData

def loadLineList(path):
    """
    Function to load a PypeIt-style line list into a 2D list.

    Args:
        path(string): The filepath to the line list.
    
    Returns:
        2D list containing formatted like a normal PypeIt line list. The list is in Row-Major order and the columns are [ion (string), wavelength (Angstroms), NIST, Instr, amplitude (float), Source (string)]
    """
    dat = pd.read_csv(path, delimiter="|")
    return dat.values[:,1:-1]

def loadLinePosAmp(path, minIntensity=1):
    """
    Function to load a PypeIt-style line list into a 2D Array. The returned array will only contain line positions and amplitudes.

    Args:
        path(string): The filepath to the line list.
        minIntensity(float, optional): The minimum intensity of lines that will be in the returned array. Default: 1

    Returns:
        2D array in Row-Major order and the columns are [wavelength (Angstroms), amplitude (float)]
    """
    dat = pd.read_csv(path, delimiter="|")
    mask = dat.values[:,5]>minIntensity
    return np.array([(dat.values[:,2])[mask], (dat.values[:,5])[mask]])